# Web Scraping and Automation of Processes with Python

Why is it important?
Allows efficient data collection without manual intervention.

Reduces time spent on repetitive tasks such as data entry or bulk uploads.

Facilitates integration with other tools and data analysis.


1️⃣ Practical cases, such as extracting data from a website and bulk data entry into platforms.


2️⃣ Process Automation using Selenium and RPA techniques.

In [7]:
 !python -m venv test

In [8]:
!test\Scripts\pip install jupyter ipykernel

Requirement already satisfied: jupyter in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (1.1.1)
Requirement already satisfied: ipykernel in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (6.29.5)
Requirement already satisfied: notebook in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter) (7.3.3)
Requirement already satisfied: jupyter-console in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter) (7.16.6)
Requirement already satisfied: ipywidgets in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter) (8.1.5)
Requirement already satisfied: jupyterlab in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter) (4.3.6)
Requirement already satisfied: comm>=0.1.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel) (0.2.2)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel) (1.8.13)
Requirement already satisfied: ipython>=7.23.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel) (9.0.2)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel) (0.1.7)
Requirement already satisfied: nest-asyncio in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel) (24.2)
Requirement already satisfied: psutil in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel) (7.0.0)
Requirement already satisfied: pyzmq>=24 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel) (26.3.0)
Requirement already satisfied: tornado>=6.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel) (6.4.2)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: colorama in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: decorator in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipython>=7.23.1->ipykernel) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.50)
Requirement already satisfied: pygments>=2.4.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipython>=7.23.1->ipykernel) (2.19.1)
Requirement already satisfied: stack_data in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-client>=6.1.12->ipykernel) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (4.3.7)
Requirement already satisfied: pywin32>=300 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (310)
Requirement already satisfied: widgetsnbextension~=4.0.12 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipywidgets->jupyter) (4.0.13)
Requirement already satisfied: jupyterlab-widgets~=3.0.12 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipywidgets->jupyter) (3.0.13)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter) (2.0.5)
Requirement already satisfied: httpx>=0.25.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter) (2.2.5)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter) (2.15.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter) (2.27.3)
Requirement already satisfied: notebook-shim>=0.2 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: setuptools>=40.8.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter) (78.1.0)
Requirement already satisfied: beautifulsoup4 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbconvert->jupyter) (4.13.3)
Requirement already satisfied: bleach!=5.0.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.2.0)
Requirement already satisfied: defusedxml in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbconvert->jupyter) (3.0.2)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbconvert->jupyter) (3.1.3)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbconvert->jupyter) (0.10.2)
Requirement already satisfied: nbformat>=5.7 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbconvert->jupyter) (5.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: webencodings in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.4.0)
Requirement already satisfied: anyio in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (4.9.0)
Requirement already satisfied: certifi in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (2025.1.31)
Requirement already satisfied: httpcore==1.* in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (1.0.7)
Requirement already satisfied: idna in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab->jupyter) (0.14.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.4)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (23.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.5.3)
Requirement already satisfied: overrides>=5.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.21.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.15)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.0)
Requirement already satisfied: babel>=2.10 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.10.0)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (4.23.0)
Requirement already satisfied: requests>=2.31 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.32.3)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbformat>=5.7->nbconvert->jupyter) (2.21.1)
Requirement already satisfied: wcwidth in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.2.13)
Requirement already satisfied: six>=1.5 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel) (1.17.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (4.13.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel) (0.2.3)
Requirement already satisfied: sniffio>=1.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from anyio->httpx>=0.25.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: argon2-cffi-bindings in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (21.2.0)
Requirement already satisfied: attrs>=22.2.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.24.0)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.3.0)
Requirement already satisfied: pyyaml>=5.3 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (6.0.2)
Requirement already satisfied: rfc3339-validator in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.3.0)
Requirement already satisfied: fqdn in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0.0)
Requirement already satisfied: uri-template in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (24.11.1)
Requirement already satisfied: cffi>=1.0.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.17.1)
Requirement already satisfied: pycparser in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.22)

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: C:\Users\Jose\OneDrive\Documentos\GitHub\Data-Science-Python\Lectures\Lecture_2\test\Scripts\python.exe -m pip install --upgrade pip

In [9]:
!test\Scripts\python -m ipykernel install --user --name=test --display-name "Python (test)"

Installed kernelspec test in C:\Users\Jose\AppData\Roaming\jupyter\kernels\test

In [2]:
!test\Scripts\pip install -r requirements.txt

Requirement already satisfied: beautifulsoup4==4.12 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from -r requirements.txt (line 1)) (4.12.0)
Requirement already satisfied: html5lib==1.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from -r requirements.txt (line 2)) (1.1)
Requirement already satisfied: ipykernel==6.29 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from -r requirements.txt (line 3)) (6.29.0)
Requirement already satisfied: ipywidgets==8.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from -r requirements.txt (line 4)) (8.1.0)
Requirement already satisfied: jupyter==1.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from -r requirements.txt (line 5)) (1.1.0)
Requirement already satisfied: lxml==5.3 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from -r requirements.txt (line 6)) (5.3.0)
Requirement already satisfied: openpyxl==3.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from -r requirements.txt (line 7)) (3.1.0)
Requirement already satisfied: pandas==2.2 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from -r requirements.txt (line 8)) (2.2.0)
Requirement already satisfied: selenium==4.28 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from -r requirements.txt (line 9)) (4.28.0)
Requirement already satisfied: tqdm==4.67 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from -r requirements.txt (line 10)) (4.67.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from beautifulsoup4==4.12->-r requirements.txt (line 1)) (2.6)
Requirement already satisfied: six>=1.9 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from html5lib==1.1->-r requirements.txt (line 2)) (1.17.0)
Requirement already satisfied: webencodings in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from html5lib==1.1->-r requirements.txt (line 2)) (0.5.1)
Requirement already satisfied: comm>=0.1.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel==6.29->-r requirements.txt (line 3)) (0.2.2)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel==6.29->-r requirements.txt (line 3)) (1.8.13)
Requirement already satisfied: ipython>=7.23.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel==6.29->-r requirements.txt (line 3)) (9.0.2)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel==6.29->-r requirements.txt (line 3)) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel==6.29->-r requirements.txt (line 3)) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel==6.29->-r requirements.txt (line 3)) (0.1.7)
Requirement already satisfied: nest-asyncio in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel==6.29->-r requirements.txt (line 3)) (1.6.0)
Requirement already satisfied: packaging in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel==6.29->-r requirements.txt (line 3)) (24.2)
Requirement already satisfied: psutil in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel==6.29->-r requirements.txt (line 3)) (7.0.0)
Requirement already satisfied: pyzmq>=24 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel==6.29->-r requirements.txt (line 3)) (26.3.0)
Requirement already satisfied: tornado>=6.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel==6.29->-r requirements.txt (line 3)) (6.4.2)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipykernel==6.29->-r requirements.txt (line 3)) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.7 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipywidgets==8.1->-r requirements.txt (line 4)) (4.0.13)
Requirement already satisfied: jupyterlab-widgets~=3.0.7 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipywidgets==8.1->-r requirements.txt (line 4)) (3.0.13)
Requirement already satisfied: notebook in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter==1.1->-r requirements.txt (line 5)) (7.3.3)
Requirement already satisfied: jupyter-console in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter==1.1->-r requirements.txt (line 5)) (6.6.3)
Requirement already satisfied: nbconvert in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter==1.1->-r requirements.txt (line 5)) (7.16.6)
Requirement already satisfied: jupyterlab in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter==1.1->-r requirements.txt (line 5)) (4.3.6)
Requirement already satisfied: et-xmlfile in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from openpyxl==3.1->-r requirements.txt (line 7)) (2.0.0)
Requirement already satisfied: numpy<2,>=1.26.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from pandas==2.2->-r requirements.txt (line 8)) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from pandas==2.2->-r requirements.txt (line 8)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from pandas==2.2->-r requirements.txt (line 8)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from pandas==2.2->-r requirements.txt (line 8)) (2025.2)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium==4.28->-r requirements.txt (line 9)) (2.3.0)
Requirement already satisfied: trio~=0.17 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from selenium==4.28->-r requirements.txt (line 9)) (0.29.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from selenium==4.28->-r requirements.txt (line 9)) (0.12.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from selenium==4.28->-r requirements.txt (line 9)) (2025.1.31)
Requirement already satisfied: typing_extensions~=4.9 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from selenium==4.28->-r requirements.txt (line 9)) (4.13.0)
Requirement already satisfied: websocket-client~=1.8 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from selenium==4.28->-r requirements.txt (line 9)) (1.8.0)
Requirement already satisfied: colorama in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from tqdm==4.67->-r requirements.txt (line 10)) (0.4.6)
Requirement already satisfied: decorator in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipython>=7.23.1->ipykernel==6.29->-r requirements.txt (line 3)) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipython>=7.23.1->ipykernel==6.29->-r requirements.txt (line 3)) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipython>=7.23.1->ipykernel==6.29->-r requirements.txt (line 3)) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipython>=7.23.1->ipykernel==6.29->-r requirements.txt (line 3)) (3.0.50)
Requirement already satisfied: pygments>=2.4.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipython>=7.23.1->ipykernel==6.29->-r requirements.txt (line 3)) (2.19.1)
Requirement already satisfied: stack_data in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from ipython>=7.23.1->ipykernel==6.29->-r requirements.txt (line 3)) (0.6.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel==6.29->-r requirements.txt (line 3)) (4.3.7)
Requirement already satisfied: pywin32>=300 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel==6.29->-r requirements.txt (line 3)) (310)
Requirement already satisfied: attrs>=23.2.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from trio~=0.17->selenium==4.28->-r requirements.txt (line 9)) (25.3.0)
Requirement already satisfied: sortedcontainers in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from trio~=0.17->selenium==4.28->-r requirements.txt (line 9)) (2.4.0)
Requirement already satisfied: idna in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from trio~=0.17->selenium==4.28->-r requirements.txt (line 9)) (3.10)
Requirement already satisfied: outcome in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from trio~=0.17->selenium==4.28->-r requirements.txt (line 9)) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from trio~=0.17->selenium==4.28->-r requirements.txt (line 9)) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from trio~=0.17->selenium==4.28->-r requirements.txt (line 9)) (1.17.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from trio-websocket~=0.9->selenium==4.28->-r requirements.txt (line 9)) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium==4.28->-r requirements.txt (line 9)) (1.7.1)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (2.0.5)
Requirement already satisfied: httpx>=0.25.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (2.2.5)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (2.15.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (2.27.3)
Requirement already satisfied: notebook-shim>=0.2 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (0.2.4)
Requirement already satisfied: setuptools>=40.8.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (78.1.0)
Requirement already satisfied: bleach!=5.0.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter==1.1->-r requirements.txt (line 5)) (6.2.0)
Requirement already satisfied: defusedxml in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbconvert->jupyter==1.1->-r requirements.txt (line 5)) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbconvert->jupyter==1.1->-r requirements.txt (line 5)) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbconvert->jupyter==1.1->-r requirements.txt (line 5)) (3.0.2)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbconvert->jupyter==1.1->-r requirements.txt (line 5)) (3.1.3)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbconvert->jupyter==1.1->-r requirements.txt (line 5)) (0.10.2)
Requirement already satisfied: nbformat>=5.7 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbconvert->jupyter==1.1->-r requirements.txt (line 5)) (5.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from nbconvert->jupyter==1.1->-r requirements.txt (line 5)) (1.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter==1.1->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: pycparser in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium==4.28->-r requirements.txt (line 9)) (2.22)
Requirement already satisfied: anyio in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (4.9.0)
Requirement already satisfied: httpcore==1.* in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (0.14.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel==6.29->-r requirements.txt (line 3)) (0.8.4)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (23.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (0.5.3)
Requirement already satisfied: overrides>=5.0 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (0.21.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (2.0.15)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in c:\users\jose\onedrive\documentos\github\data-science-python\lectures\lecture_2\test\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter==1.1->-r requirements.txt (line 5)) (0.18.1)

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: C:\Users\Jose\OneDrive\Documentos\GitHub\Data-Science-Python\Lectures\Lecture_2\test\Scripts\python.exe -m pip install --upgrade pip

In [3]:
!python --version

Python 3.12.7

In [6]:
!python -m venv test ## creas un entorno llamado "test"

In [10]:
!C:\Users\Jose\OneDrive\Documentos\GitHub\Data-Science-Python\Lectures\Lecture_2\test\Scripts -m pip install --upgrade pip

"C:\Users\Jose\OneDrive\Documentos\GitHub\Data-Science-Python\Lectures\Lecture_2\test\Scripts" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

In [ ]:
!C:\Users\Jose\OneDrive\Documentos\GitHub\Data-Science-Python\Lectures\Lecture_2\test\Scripts -m ipykernel install --user=test --display

In [4]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

In [5]:
# Inicializar el WebDriver
driver = webdriver.Chrome()
driver.maximize_window()

# URL
url = 'https://www.rpachallenge.com/'
driver.get(url)

# Click of element
stock_market_link = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.LINK_TEXT, "RPA Stock Market"))
)
stock_market_link.click()

In [6]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

# Set up Selenium
driver = webdriver.Chrome()
driver.maximize_window()
driver.maximize_window()

# Navigate to the RPA Challenge website
url = 'https://www.rpachallenge.com/'
driver.get(url)

# Click on the "RPA Stock Market" link
stock_market_link = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.LINK_TEXT, "RPA Stock Market"))
)
stock_market_link.click()

# List to store stock prices
data = []

try:
    while True:
        # Find the price on the page (adjust the XPath according to the website structure)
        price_element = driver.find_element(By.XPATH, "//*[@id='cnt']")  # Adjust XPath if needed
        price = price_element.text

        # Save the timestamp and price
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
        data.append([timestamp, price])

        # Print to the console
        print(f"{timestamp} - Price: {price}")

        # Wait 1 second before the next capture
        time.sleep(1)

except KeyboardInterrupt:
    print("Scraping stopped by user.")

    # Save data to a DataFrame and export to CSV
    df = pd.DataFrame(data, columns=["Timestamp", "Price"])
    df.to_csv("stock_prices.csv", index=False)
    print("Data saved in 'stock_prices.csv'.")

finally:
    driver.quit()

2025-03-26 06:44:16 - Price: 70.65
2025-03-26 06:44:17 - Price: 70.65
2025-03-26 06:44:18 - Price: 70.65
2025-03-26 06:44:19 - Price: 77.35

AttributeError: 'NoneType' object has no attribute 'text'

In [35]:
type(data)

list

In [36]:
# Convert to DataFrame
dataframe = pd.DataFrame(data, columns=["Time","price"])
dataframe

                   Time  price
0   2025-03-23 00:55:35  77.35
1   2025-03-23 00:55:36  77.35
2   2025-03-23 00:55:37  77.35
3   2025-03-23 00:55:38   76.9
4   2025-03-23 00:55:39   76.9
5   2025-03-23 00:55:40   76.9
6   2025-03-23 00:55:41  76.25
7   2025-03-23 00:55:42  76.25
8   2025-03-23 00:55:43  76.25
9   2025-03-23 00:55:44   75.8
10  2025-03-23 00:55:45   75.8
11  2025-03-23 00:55:46  75.15
12  2025-03-23 00:55:47  75.15
13  2025-03-23 00:55:48  75.15
14  2025-03-23 00:55:49   74.7
15  2025-03-23 00:55:50   74.7
16  2025-03-23 00:55:51   74.7
17  2025-03-23 00:55:52  74.05
18  2025-03-23 00:55:53  74.05
19  2025-03-23 00:55:54  74.05
20  2025-03-23 00:55:55   73.6
21  2025-03-23 00:55:56   73.6

## AUTOMATION OF PROCESS WITH PYTHON
## CREATE OF RPA (ROBOT PROCESS AUTOMATION)

In [10]:
import pandas as pd  

# Load the Excel file using a relative path
df = pd.read_excel("././challenge.xlsx")

df

,First Name,Last Name,Company Name,Role in Company,Address,Email,Phone Number
0,John,Smith,IT Solutions,Analyst,98 North Road,jsmith@itsolutions.co.uk,40716543298
1,Jane,Dorsey,MediCare,Medical Engineer,11 Crown Street,jdorsey@mc.com,40791345621
2,Albert,Kipling,Waterfront,Accountant,22 Guild Street,kipling@waterfront.com,40735416854
3,Michael,Robertson,MediCare,IT Specialist,17 Farburn Terrace,mrobertson@mc.com,40733652145
4,Doug,Derrick,Timepath Inc.,Analyst,99 Shire Oak Road,dderrick@timepath.co.uk,40799885412
5,Jessie,Marlowe,Aperture Inc.,Scientist,27 Cheshire Street,jmarlowe@aperture.us,40733154268
6,Stan,Hamm,Sugarwell,Advisor,10 Dam Road,shamm@sugarwell.org,40712462257
7,Michelle,Norton,Aperture Inc.,Scientist,13 White Rabbit Street,mnorton@aperture.us,40731254562
8,Stacy,Shelby,TechDev,HR Manager,19 Pineapple Boulevard,sshelby@techdev.com,40741785214
9,Lara,Palmer,Timepath Inc.,Programmer,87 Orange Street,lpalmer@timepath.co.uk,40731653845

In [ ]:
df.columns

In [ ]:
# rename columns
df = pd.read_excel("././challenge.xlsx")

df = df.rename(columns={"First Name": "First_name", "Last Name ": "Last_name", "Company Name": "Company",
                        "Phone Number": "Phone_number","Role in Company":"Role_Company"})
df.columns

We need to upload the information from a form response to the company's website.

### Import libreries

In [11]:
# This library is to manipulate the browser
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium.webdriver.chrome.service import Service
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException
from selenium.webdriver import ActionChains

# WebDriver Manager
from webdriver_manager.chrome import ChromeDriverManager

# Standard libraries
import pandas as pd
import numpy as np
import os
import time
import re
from unidecode import unidecode

In [ ]:
# First, we will click on the phone element using its reflect name.
phone = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, "//input[@ng-reflect-name='labelPhone']"))
)
phone.click()

In [ ]:
first = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, "//input[@ng-reflect-name='labelFirstName']"))
)

first.click()

In [ ]:
last = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, "//input[@ng-reflect-name='labelLastName']"))
)
last.click()

In [ ]:
role = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, "//input[@ng-reflect-name='labelRole']"))
)

role.click()

In [ ]:
email = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, "//input[@ng-reflect-name='labelEmail']"))
)
email.click()

In [ ]:
address = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, "//input[@ng-reflect-name='labelAddress']"))
)
address.click()

In [ ]:
company = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, "//input[@ng-reflect-name='labelCompanyName']"))
)
company,click()

In [ ]:
start = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, "//button[contains(text(), 'Start')]"))
)
start.click()

In [ ]:
submit_button = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.CLASS_NAME, "btn"))
)
submit_button.click()

In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
import pandas as pd

In [7]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
import pandas as pd

# Initialize the WebDriver
driver = webdriver.Chrome()
driver.maximize_window()

# Challenge URL
url = 'https://www.rpachallenge.com/'
driver.get(url)

time.sleep(2)  # Wait for the page to load

# Click the "Start" button
start_button = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.XPATH, "//button[contains(text(), 'Start')]"))
)
start_button.click()

# Define column mapping
column_to_web = {
    "First_name": "labelFirstName",
    "Last_name": "labelLastName",
    "Phone_number": "labelPhone",
    "Email": "labelEmail",
    "Address": "labelAddress",
    "Company": "labelCompanyName",
    "Role_Company": "labelRole"
}

# Load the DataFrame
df = pd.read_excel("./challenge.xlsx").rename(columns={
    "First Name": "First_name",
    "Last Name ": "Last_name",
    "Company Name": "Company",
    "Phone Number": "Phone_number",
    "Role in Company": "Role_Company"
})

# Function to fill input fields
def fill_input_field(driver, field_name, value):
    field = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, f"//input[@ng-reflect-name='{field_name}']"))
    )
    driver.execute_script("arguments[0].scrollIntoView();", field)
    field.click()
    field.clear()
    field.send_keys(value)
    time.sleep(1)

# Function to click "Submit"
def click_submit(driver):
    submit_button = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, "//input[@class='btn uiColorButton' and @type='submit']"))
    )
    driver.execute_script("arguments[0].scrollIntoView();", submit_button)
    submit_button.click()
    time.sleep(2)

# Iterate through each row of the DataFrame and fill in the data
for index, row in df.iterrows():
    print(f"Filling data for: {row['First_name']} {row['Last_name']}")

    for col_df, web_name in column_to_web.items():
        fill_input_field(driver, web_name, row[col_df])

    click_submit(driver)  # Click "Submit" after completing a row

print("Finished Work")

Filling data for: John Smith
Filling data for: Jane Dorsey
Filling data for: Albert Kipling
Filling data for: Michael Robertson
Filling data for: Doug Derrick
Filling data for: Jessie Marlowe
Filling data for: Stan Hamm
Filling data for: Michelle Norton
Filling data for: Stacy Shelby
Filling data for: Lara Palmer
Finished Work

In [40]:
manual=30 * 7
minut=manual / 60 

print(f"{minut:.2f} minutes")

3.50 minutes

In [39]:
milliseconds = 101160

seconds = milliseconds / 1000  # Convert to seconds
minutes = seconds / 60  # Convert to minutes

print(f"{milliseconds} ms = {seconds:.2f} seconds")
print(f"{milliseconds} ms = {minutes:.2f} minutes")

101160 ms = 101.16 seconds
101160 ms = 1.69 minutes